version: "3"

tasks:
  default:
    cmds:
      - cp exec.sql.sample exec.sql
      - ./duckadmin.sh exec.sql
  python-*:
    vars:
      FILE: '{{index .MATCH 0}}'
    cmds:
      - ./duckpy.sh {{.FILE}}
